# LNSC Bayesian Hyperparameter Optimization Configuration

# Data paths
data_path: "data/processed/lnsc_invivo_preprocessed.h5ad"  # Path to preprocessed h5ad file from Seurat
output_dir: "results/lnsc_optimization"

# GPU settings
gpu_memory_gb: 16  # Memory pool size in GB
device_id: 0       # GPU device to use

# Random seed for reproducibility
random_state: 42

# Biological markers based on Rodda et al. 2018
markers:
  tier1_markers:
    FDC:
      - Cr2
      - Coch
      - Fcgr2b
    MRC:
      - Madcam1
      - Tnfsf11  # RANKL
    Medullary:
      - Inmt
    CD34_stromal:
      - Cd34
      - Pi16
      - Cxcl14
    TRC_core:
      - Ccl19
      - Ccl21a  # Note: might be Ccl21 in some datasets
      - Il7
      - Pdpn
  
  gradient_markers:
    TRC_subtypes:
      Ccl19:
        high: 2.5
        low: [1.0, 2.5]
    Inflammatory:
      - Cxcl9
      - Cxcl10
    Activation:
      - Nr4a1
  
  # Thresholds for marker evaluation
  thresholds:
    min_fold_change: 2.0
    max_pvalue: 0.05
    min_pct_expressing: 0.25

# Optimization parameters
optimization:
  # Parameter search ranges
  param_ranges:
    n_pcs:
      min: 10
      max: 50
    n_neighbors:
      min: 10
      max: 50
    min_dist:
      min: 0.01
      max: 0.5
    resolution:
      min: 0.1
      max: 2.0
  
  # Scoring weights (must sum to 1.0)
  score_weights:
    tier1_specificity: 0.35
    gradient_separation: 0.25
    marker_coverage: 0.20
    rare_population_score: 0.10
    stability: 0.10

# Validation samples (optional)
validation_samples:
  - "data/processed/lnsc_2d_invitro_preprocessed.h5ad"
  - "data/processed/lnsc_3d_invitro_preprocessed.h5ad"

# Optuna settings
optuna:
  n_trials: 100
  n_jobs: 1  # Set >1 for parallel trials (requires sufficient GPU memory)
  pruner:
    n_startup_trials: 10
    n_warmup_steps: 5

# Logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"